import Config

# This file is generated by dockerize. It is used for holding sensitive
# runtime configurations.  For more information about runtime configuration
# for mix release, please check the documentation:
# - https://hexdocs.pm/mix/Mix.Tasks.Release.html#module-runtime-configuration
#
# Example:
#
#    config :my_app, MyApp.Repo,
#      adapter: Ecto.Adapters.Postgres,
#      username: System.fetch_env!("DB_USERNAME"),
#      password: System.fetch_env!("DB_PASSWORD"),
#      hostname: System.fetch_env!("DB_HOSTNAME"),
#      port: System.fetch_env!("DB_PORT"),
#      database: System.fetch_env!("DB_DATABASE"),
#      pool_size: 20

# config :blog, :secret_key, System.fetch_env!("MY_APP_SECRET_KEY")
config :qiu_blog, :fly,
  region: System.get_env("FLY_REGION", "unknown"),
  alloc_id: System.get_env("FLY_ALLOC_ID", "unknown")

config :qiu_blog, QiuBlogWeb.Endpoint,
  secret_key_base:
    System.get_env(
      "SECRET_KEY_BASE",
      "jtKc24LNHxYfLoMocwmeRCArpoDQ1jqwAzB89ZJlK8Fkwl0q7BVI9fiuVVLlust4"
    )
